services:
  web-installer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    container_name: android-web-installer
    restart: unless-stopped
